name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install mpich
        wget https://github.com/FreeFem/FreeFem-sources/releases/download/v4.13/FreeFEM-4.13-amd64-ubuntu20.04.deb
        sudo apt install FreeFEM-4.13-amd64-ubuntu20.04.deb
    - name: configure
      run: autoreconf -i && ./configure --with-dependencies
    - name: make
      run: make && make install
    - name: make check
      run: make check
